#!/usr/bin/env bash


if [[ $1 == 'applauncher'    ]]; then rofi -show drun; fi
if [[ $1 == 'pavu'           ]]; then pavucontrol; fi
if [[ $1 == 'network'        ]]; then network; fi
if [[ $1 == 'rog'            ]]; then rog-control-center; fi
if [[ $1 == 'brightness'     ]]; then wl-gammactl; fi
if [[ $1 == 'bluetooth'      ]]; then blueberry; fi
if [[ $1 == 'powermenu'      ]]; then powermenu; fi
if [[ $1 == 'toggle_menu'    ]]; then toggle_menu $2; fi
if [[ $1 == 'close_calendar' ]]; then close_calendar; fi
if [[ $1 == 'colorpicker'    ]]; then colorpicker; fi
if [[ $1 == 'picker'         ]]; then picker; fi
if [[ $1 == 'screenlock'     ]]; then screenlock; fi
if [[ $1 == 'config'         ]]; then config; fi
if [[ $1 == 'screenshot'     ]]; then screenshot $2; fi

if [[ $1 == 'firefox'       ]]; then LibreWolf; fi
if [[ $1 == 'terminal'      ]]; then footclient; fi
if [[ $1 == 'file-manager'  ]]; then thunar; fi
if [[ $1 == 'wall-change'   ]]; then ~/.config/sway/scripts/wallpaper_change.sh; fi
if [[ $1 == 'bluetooth'     ]]; then ~/.config/rofi/scripts/rofi-bluetooth; fi
