export PATH="$HOME/.cargo/bin:$PATH"
export SDL_VIDEODRIVER=WAYLAND
export _JAVA_AWT_WM_NONREPARENTING=1
export QT_QPA_PLATFORM=WAYLAND
export XDG_CURRENT_DESKTOP=sway
export XDG_SESSION_DESKTOP=SWAY
