#!/usr/bin/bash

source ~/.cache/wal/colors.sh
exec swaylock                         \
	--show-failed-attempts              \
  --image ~/Pictures/wallhaven-4oj627.jpg                       \
	--bs-hl-color AD706D                \
	--font FiraCode Nerd Font           \
	--font-size 33                      \
	--scaling fill                      \
	--show-keyboard-layout              \
	--indicator-idle-visible            \
	--indicator-radius 150              \
	--indicator-thickness 4  	  	      \
--inside-color=#bc65a16d   \
--inside-clear-color=#d5b24c55   \
--inside-caps-lock-color=#7fbae706   \
--inside-ver-color=#918374da   \
--inside-wrong-color=#78b08bca   \
--key-hl-color=#3e2032e8   \
--layout-bg-color=#faecbb75   \
--layout-border-color=#f0a95db0   \
--layout-text-color=#d6cc9a79   \
--line-color=#f5ba683c   \
--line-clear-color=#419edce0   \
--line-caps-lock-color=#629bc74e   \
--line-ver-color=#a100bf12   \
--line-wrong-color=#1f61937f   \
--ring-color=#74195c9c   \
--ring-clear-color=#81c2382b   \
--ring-caps-lock-color=#580fea6e   \
--ring-ver-color=#b6232eac   \
--ring-wrong-color=#89a7b25f   \
--separator-color=#a165832c   \
--text-color=#cc841dff   \
--text-clear-color=#f088027b   \
--text-caps-lock-color=#0b4147e0   \
--text-ver-color=#d41684ab   \
--text-wrong-color=#68956e7d   \
	--grace 2                           \   \
	--fade-in 0.2                       \
	--clock                             \
	--timestr '%H:%M'                   \
	--datestr '%Y-%m-%d'                \
	--indicator                         \
