#!/bin/sh
source ~/.cache/wal/colors-river.sh
#######################################################################
#######################################################################
riverctl map normal Super Return spawn foot
riverctl map -layout 0 normal Super Z spawn fuzzel
riverctl map -layout 0 normal Super F3 spawn "foot -T Neovim nvim"
riverctl map -layout 0 normal Super F2 spawn "foot -T Yazi yazi"
riverctl map -layout 0 normal None Print spawn grim
riverctl map -layout 0 normal Super+Shift Z spawn "~/.local/bin/powermenu"
riverctl map -layout 0 normal Super+Shift T spawn "bash ~/.dotfiles/.config/waybar/scripts/gammastep/gamma_toggle.sh"

riverctl spawn "~/.config/river/scripts/lockscreen.sh"


#######################################################################
# The scratchpad will live on an unused tag. Which tags are used depends on your
# config, but rivers default uses the first 9 tags.
scratch_tag=$((1 << 20 ))

# Toggle the scratchpad with Super+P
riverctl map -layout 0 normal Super A toggle-focused-tags ${scratch_tag}

# Send windows to the scratchpad with Super+Shift+P
riverctl map -layout 0 normal Super+Shift A set-view-tags ${scratch_tag}

# Set spawn tagmask to ensure new windows don't have the scratchpad tag unless
# explicitly set.
all_but_scratch_tag=$(( ((1 << 32) - 1) ^ $scratch_tag ))
riverctl spawn-tagmask ${all_but_scratch_tag}

#######################################################################

riverctl map -layout 0 normal Super up    send-layout-cmd wideriver "--layout monocle"
riverctl map -layout 0 normal Super down  send-layout-cmd wideriver "--layout top"
riverctl map -layout 0 normal Super left  send-layout-cmd wideriver "--layout left"
riverctl map -layout 0 normal Super right send-layout-cmd wideriver "--layout right"

riverctl map -layout 0 normal Super E     send-layout-cmd wideriver "--stack even"
riverctl map -layout 0 normal Super W     send-layout-cmd wideriver "--stack dwindle"
riverctl map -layout 0 normal Super I     send-layout-cmd wideriver "--stack diminish"

riverctl map normal Super plus  send-layout-cmd wideriver "--ratio +0.025"    
riverctl map normal Super equal send-layout-cmd wideriver "--ratio 0.35"      
riverctl map normal Super minus send-layout-cmd wideriver "--ratio -0.025"    
     
#######################################################################
#######################################################################

# Super+Q to close the focused view
riverctl map -layout 0 normal Super Q close

# Super+Shift+E to exit river
riverctl map -layout 0 normal Super+Shift E exit

# Super+J and Super+K to focus the next/previous view in the layout stack
riverctl map -layout 0 normal Super J focus-view next
riverctl map -layout 0 normal Super K focus-view previous

# Super+Shift+J and Super+Shift+K to swap the focused view with the next/previous
# view in the layout stack
riverctl map -layout 0 normal Super+Shift J swap next
riverctl map -layout 0 normal Super+Shift K swap previous

# Super+Period and Super+Comma to focus the next/previous output
riverctl map -layout 0 normal Super Period focus-output next
riverctl map -layout 0 normal Super Comma focus-output previous

# Super+Shift+{Period,Comma} to send the focused view to the next/previous output
riverctl map -layout 0 normal Super+Shift Period send-to-output next
riverctl map -layout 0 normal Super+Shift Comma send-to-output previous

# Super+Control Return to bump the focused view to the top of the layout stack
riverctl map -layout 0 normal Super+Control Return zoom

# Super+Alt+{H,J,K,L} to move views
riverctl map -layout 0 normal Super+Alt H move left 100
riverctl map -layout 0 normal Super+Alt J move down 100
riverctl map -layout 0 normal Super+Alt K move up 100
riverctl map -layout 0 normal Super+Alt L move right 100

# Super+Alt+Control+{H,J,K,L} to snap views to screen edges
riverctl map -layout 0 normal Super+Alt+Control H snap left
riverctl map -layout 0 normal Super+Alt+Control J snap down
riverctl map -layout 0 normal Super+Alt+Control K snap up
riverctl map -layout 0 normal Super+Alt+Control L snap right

# Super+Alt+Shift+{H,J,K,L} to resize views
riverctl map -layout 0 normal Super+Alt+Shift H resize horizontal -100
riverctl map -layout 0 normal Super+Alt+Shift J resize vertical 100
riverctl map -layout 0 normal Super+Alt+Shift K resize vertical -100
riverctl map -layout 0 normal Super+Alt+Shift L resize horizontal 100

# Super + Left Mouse Button to move views
riverctl map-pointer normal Super BTN_LEFT move-view

# Super + Right Mouse Button to resize views
riverctl map-pointer normal Super BTN_RIGHT resize-view

# Super + Middle Mouse Button to toggle float
riverctl map-pointer normal Super BTN_MIDDLE toggle-float

for i in $(seq 1 9)
do
    tags=$((1 << ($i - 1)))

    # Super+[1-9] to focus tag [0-8]
    riverctl map normal Super $i set-focused-tags $tags

    # Super+Shift+[1-9] to tag focused view with tag [0-8]
    riverctl map normal Super+Shift $i set-view-tags $tags

    # Super+Control+[1-9] to toggle focus of tag [0-8]
    riverctl map normal Super+Control $i toggle-focused-tags $tags

    # Super+Shift+Control+[1-9] to toggle tag [0-8] of focused view
    riverctl map normal Super+Shift+Control $i toggle-view-tags $tags
done

# Super+0 to focus all tags
# Super+Shift+0 to tag focused view with all tags
all_tags=$(((1 << 32) - 1))
riverctl map normal Super 0 set-focused-tags $all_tags
riverctl map normal Super+Shift 0 set-view-tags $all_tags

# Super+Space to toggle float
riverctl map normal Super Space toggle-float

# Super+F to toggle fullscreen
riverctl map -layout 0 normal Super F toggle-fullscreen

# Declare a passthrough mode. This mode has only a single mapping to return to
# normal mode. This makes it useful for testing a nested wayland compositor
riverctl declare-mode passthrough

# Super+F11 to enter passthrough mode
riverctl map normal Super F11 enter-mode passthrough

# Super+F11 to return to normal mode
riverctl map passthrough Super F11 enter-mode normal

# Various media key mapping examples for both normal and locked mode which do
# not have a modifier
for mode in normal locked
do
    # Eject the optical drive (well if you still have one that is)
    # riverctl map $mode None XF86Eject spawn 'eject -T'

    # Control pulse audio volume with pamixer (https://github.com/cdemoulins/pamixer)
   #  riverctl map $mode None XF86AudioRaiseVolume  spawn 'pamixer -i 5'
   #  riverctl map $mode None XF86AudioLowerVolume  spawn 'pamixer -d 5'
   #  riverctl map $mode None XF86AudioMute         spawn 'pamixer --toggle-mute'
	 #  Control MPRIS aware media players with playerctl (https://github.com/altdesktop/playerctl)
   #  riverctl map $mode None XF86AudioMedia spawn 'playerctl play-pause'
   #  riverctl map $mode None XF86AudioPlay  spawn 'playerctl play-pause'
   #  riverctl map $mode None XF86AudioPrev  spawn 'playerctl previous'
   #  riverctl map $mode None XF86AudioNext  spawn 'playerctl next'

    # Control screen backlight brightness with light (https://github.com/haikarainen/light)
    riverctl map $mode None XF86MonBrightnessUp   spawn 'light -S 100'
    riverctl map $mode None XF86MonBrightnessDown spawn 'light -S 0'
done

# Set background and border color
riverctl background-color 0x000000
#riverctl border-color-focused 0xff2cb3
#riverctl border-color-unfocused 0x586e75
#riverctl border-color-urgent 0xaaaaaa
#riverctl border-width 1

# Cursor
riverctl focus-follows-cursor always
riverctl hide-cursor when-typing enabled
riverctl hide-cursor timeout 0
riverctl set-cursor-warp on-output-change

# Input
riverctl input pointer-2-7-SynPS/2_Synaptics_TouchPad middle-emulation enabled
riverctl input pointer-2-7-SynPS/2_Synaptics_TouchPad natural-scroll enabled
riverctl input pointer-2-7-SynPS/2_Synaptics_TouchPad scroll-factor 2
riverctl input pointer-2-7-SynPS/2_Synaptics_TouchPad tap enabled
riverctl input pointer-2-7-SynPS/2_Synaptics_TouchPad tap-button-map left-right-middle
riverctl input pointer-2-7-SynPS/2_Synaptics_TouchPad scroll-method two-finger
riverctl input pointer-2-7-SynPS/2_Synaptics_TouchPad accel-profile adaptive

riverctl input pointer-4815-341-COOLER_MASTER_CM_STORM_SENTINEL_Z3RO-G accel-profile flat
riverctl input pointer-4815-341-COOLER_MASTER_CM_STORM_SENTINEL_Z3RO-G pointer-accel -0.1

riverctl keyboard-layout -options "grp:alt_shift_toggle,caps:escape,altwin:menu_win" -model "pc86" "us,ru"

# Set keyboard repeat rate
riverctl set-repeat 25 300

#######################################################################
#######################################################################
# Make all views with an app-id that starts with "float" and title "foo" start floating.
riverctl rule-add -app-id 'float*' -title 'foo' float

# Make all views with app-id "bar" and any title use client-side decorations
riverctl rule-add -app-id "bar" csd
riverctl rule-add ssd

# riverctl rule-add -app-id "mpv" float
riverctl rule-add -app-id "smplayer" float
riverctl rule-add -app-id "gcolor3" float
riverctl rule-add -app-id "thunar" ssd
riverctl rule-add -app-id "org.pwmt.zathura" ssd
riverctl rule-add -title "File Operation Progress" float
riverctl rule-add -title "Song Info" float
riverctl rule-add -title "TelegramDesktop" float
riverctl rule-add -title "TelegramDesktop" position 1100 100
riverctl rule-add -title "Enter name of file to save to…" float
riverctl rule-add -title "Enter name of file to save to…" dimensions 1000 600

# Set the default layout generator to be rivertile and start it.
# River will send the process group of the init executable SIGTERM on exit.
riverctl default-layout wideriver

# start layout manager
wideriver \
    --layout                       left        \
    --layout-alt                   monocle     \
    --stack                        dwindle     \
    --count-master                 1           \
    --ratio-master                 0.50        \
    --count-wide-left              0           \
    --ratio-wide                   0.35        \
    --inner-gaps                   2           \
    --outer-gaps                   0           \
    --border-width                 2           \
    --border-width-monocle         1           \
    --border-width-smart-gaps      1           \
    --border-color-focused         "0x874135"  \
    --border-color-focused-monocle "0x22809f"  \
    --border-color-unfocused       "0x586e75"  \
    --log-threshold                info        \
   > "/tmp/wideriver.${XDG_VTNR}.${USER}.log" 2>&1 &

waybar -c ~/.config/waybar/for_river/config           \
			 -s ~/.config/waybar/for_river/style.css        &
kanshi                                                &
dunst                                                 &
pipewire                                              &
light -S 50                                           &
wl-paste -t text --watch clipman store --no-persist   &
blueman-applet                                        &
udiskie --tray                                        &
sleep 1 && swww-daemon                                &
# eww daemon && eww open dock                           &
