#!/bin/bash

xsetroot -cursor_name left_ptr &
xset fp+ ~/.local/share/fonts &
xset s 540 60 &
xautolock -time 8 -locker "/home/rengoku/.config/bspwm/lock.sh" &
light -S 50 &
xrdb -merge ~/.Xresources &
pgrep -x sxhkd > /dev/null || sxhkd &
nitrogen --restore &
nm-applet&
blueman-applet &
pulseaudio &
pgrep -x fbxkb > /dev/null || fbxkb &
setxkbmap -option grp:alt_shift_toggle us,ru & 
pgrep -x udiskie > /dev/null || udiskie --tray &

#xrandr --output VGA-0 --mode 1280x1024 --rate 75

# borders
BW=2
bspc config border_width $BW
 bspc config window_gap -$BW
for side in top right bottom left ; do
	bspc config ${side}_padding $BW
done

bspc config window_gap  0
bspc config focused_border_color   "#940094"
bspc config normal_border_color    "#44475a"
bspc config active_border_color    "#ff79c6"
bspc config presel_feedback_color  "#6272a4"


bspc config split_ratio		0.52
bspc config focus_follows_pointer	true
bspc config pointer_modifier	mod4
bspc config automatic_scheme	spiral

bspc rule -a Firefox desktop='^1'
bspc rule -a Nitrogen state=floating rectangle=800x600+15+15
bspc rule -a mpv state=floating 

# desktops
bspc monitor VGA-0 -d     
bspc monitor LVDS -d      

$HOME/.config/polybar/launch.sh --forest &

