#!/usr/bin/bash
swayidle -w \
	timeout 570 'notify-send -h string:bgcolor:#900000 -h string:fgcolor:#ffffff -h string:frcolor:#ff0000 "LOCKING screen in 30 seconds"'  \
	timeout 600 '"gtklock -f -S --idle-hide --idle-timeout 3"' \
